version: '2'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    volumes:
      - backend-sync:/app:delegated
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=password
      - DB_NAME=taskflow
      - JWT_SECRET_KEY=R6wFmz6f8FvXh3z5JnkQwtxmfgWnmZ0H+vRY9TjlVw8=
    command: sh -c "go mod tidy && go mod download && air"
    depends_on:
      - postgres
    networks:
      - taskflow-network

  frontend:
    build:
      context: ./frontend
    environment:
      - CHOKIDAR_USEPOLLING=true  # Включаем поллинг для обнаружения изменений на Windows/MacOS
    command: sh -c "npm install && npm run start"  # Команда для установки зависимостей и запуска dev-сервера
    ports:
      - "3000:3000"
    volumes:
      - frontend-sync:/app:delegated
    networks:
      - taskflow-network
    depends_on:
      - backend

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - taskflow-network

networks:
  taskflow-network:
    driver: bridge

volumes:
  postgres_data:
  frontend-sync:
    external: true
  backend-sync:
    external: true