version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    networks:
      - taskflow-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - taskflow-network
    depends_on:
      - backend

networks:
  taskflow-network:
    driver: bridge
